### ISSUE TITLE
Can not sell/put things on horse-wagon

### ISSUE THREAD

**Issue by Wollffus** [CryptoGenics/redemrp_butcher#2]
When i put this resource in, i can see the butcher blips. 
Whenever this resource is running, we can not put animals on our horses or wagons, or pelts either. 
When you take a pelt to the butcher or a full animal there is no sell command. ?

**Comment by CryptoGenics** [comment]
This script is not designed to have anything to do with horses and or wagons. Simply hold a pelt or carcass while infront of a butcher table to get a sell prompt. I have updated the readme as well, hope this helps.
